# Generated by Django 5.0.6 on 2024-07-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='left',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
