# Generated by Django 5.0.6 on 2024-07-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_login_code_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passed_login_code',
            field=models.BooleanField(blank=True, null=True, verbose_name='Passed Login Code?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Login Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
